# -*- coding: utf-8 -*-
from . import views
from django.contrib import admin
from django.urls import path

#Redirected from urls.py FirstProject and allows website to respond to requests
# by feeding html generated by and attached to the accompanying views.
urlpatterns = [
    path('', views.Home, name="Home"), 
    path('sales/', views.Sales, name="Sales"),   
    path('products/',views.Products, name="Products"),
    path('customers/',views.Customers, name="Customers"),
    path('leads/',views.Leads, name="Leads"),
    path('sales/<str:sale_id>', views.Sales2, name="Dy_Sales"),
    path('products/<str:Product_id>', views.Products2, name="Dy_Products"),
    path('customers/<str:Customer_id>',views.Customers2, name="Dy_Customers"),
    path('leads/<str:Lead_id>',views.Leads2, name="Dy_Leads"),
]